version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - MILVUS_URI=${MILVUS_URI}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}
    ports:
      - "8000:8000"
    restart: always