version: '3'
services:
  ec2_fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - MILVUS_URI=${MILVUS_URI}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
      - BUCKET=${BUCKET}
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - REGION=${REGION}
    ports:
      - "8000:8000"
    restart: always
    networks:
      - shared_network

networks:
  shared_network:
    external: true